In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [3]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [4]:
df.shape

(898, 35)

In [5]:
X = df.drop(['Class'], axis='columns')
y = df.Class

In [6]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [7]:
y.head()

0    BERHI
1    BERHI
2    BERHI
3    BERHI
4    BERHI
Name: Class, dtype: str

In [8]:
y.unique()

<StringArray>
['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY']
Length: 7, dtype: str

In [10]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
)

In [18]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
import torch 
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [20]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [21]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [22]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

In [28]:
# build our Model

class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()

        self.model = nn.Sequential(
            # 1st Hidden Layer
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),

            # 2nd Hidden Layer
            nn.Linear(64,64),
            nn.ReLU(),

            # output Layer
            nn.Linear(64,7)
        )
    def forward(self,x):
        return self.model(x)

In [29]:
model = ANN()

# Loss & Optim

criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [30]:
# Train the nn

epochs = 100

for epoch in range(epochs):
    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()

        outputs = model(xb)
        loss = criteria(outputs, yb)
        loss.backward()
        optimizer.step() # params update

        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)

    print(f"epoch ==> {epoch+1} / {epochs} train loss {train_loss} ")

epoch ==> 1 / 100 train loss 1.710304591966712
epoch ==> 2 / 100 train loss 1.1050454663193745
epoch ==> 3 / 100 train loss 0.7167211447073065
epoch ==> 4 / 100 train loss 0.5330870086732118
epoch ==> 5 / 100 train loss 0.4456622963366301
epoch ==> 6 / 100 train loss 0.3998501339684362
epoch ==> 7 / 100 train loss 0.34423406357350556
epoch ==> 8 / 100 train loss 0.3237703870172086
epoch ==> 9 / 100 train loss 0.2913023563830749
epoch ==> 10 / 100 train loss 0.2683284114236417
epoch ==> 11 / 100 train loss 0.25300935623438464
epoch ==> 12 / 100 train loss 0.243583294360534
epoch ==> 13 / 100 train loss 0.22515820096368375
epoch ==> 14 / 100 train loss 0.22100166522938272
epoch ==> 15 / 100 train loss 0.2077191640501437
epoch ==> 16 / 100 train loss 0.19786154041471687
epoch ==> 17 / 100 train loss 0.19619081979212555
epoch ==> 18 / 100 train loss 0.1818164732793103
epoch ==> 19 / 100 train loss 0.17834384221097696
epoch ==> 20 / 100 train loss 0.17102560328076716
epoch ==> 21 / 100 train loss 0.1652291498106459
epoch ==> 22 / 100 train loss 0.16113057894551236
epoch ==> 23 / 100 train loss 0.14848500644059284
epoch ==> 24 / 100 train loss 0.14646010667733525
epoch ==> 25 / 100 train loss 0.1578381817949855
epoch ==> 26 / 100 train loss 0.1440451245592988
epoch ==> 27 / 100 train loss 0.13688782991274542
epoch ==> 28 / 100 train loss 0.13574934151509535
epoch ==> 29 / 100 train loss 0.12969570064350314
epoch ==> 30 / 100 train loss 0.12509575194638708
epoch ==> 31 / 100 train loss 0.12266594414477763
epoch ==> 32 / 100 train loss 0.12871603716326796
epoch ==> 33 / 100 train loss 0.1172005093615988
epoch ==> 34 / 100 train loss 0.1141240073610907
epoch ==> 35 / 100 train loss 0.1112487790701182
epoch ==> 36 / 100 train loss 0.10738521506604941
epoch ==> 37 / 100 train loss 0.10392042492394862
epoch ==> 38 / 100 train loss 0.10299949898667958
epoch ==> 39 / 100 train loss 0.1052724422644014
epoch ==> 40 / 100 train loss 0.09931364947039148
epoch ==> 41 / 100 train loss 0.09663934406378995
epoch ==> 42 / 100 train loss 0.09832273415573266
epoch ==> 43 / 100 train loss 0.09764581311332143
epoch ==> 44 / 100 train loss 0.09201559861717017
epoch ==> 45 / 100 train loss 0.09157561703139673
epoch ==> 46 / 100 train loss 0.08922153662728227
epoch ==> 47 / 100 train loss 0.09029310723037823
epoch ==> 48 / 100 train loss 0.08657210393120414
epoch ==> 49 / 100 train loss 0.08761939365902673
epoch ==> 50 / 100 train loss 0.0917731411755085
epoch ==> 51 / 100 train loss 0.08861588832476865
epoch ==> 52 / 100 train loss 0.07972882194039614
epoch ==> 53 / 100 train loss 0.07307426785321339
epoch ==> 54 / 100 train loss 0.0735985690160938
epoch ==> 55 / 100 train loss 0.07166994755844706
epoch ==> 56 / 100 train loss 0.08089100269843703
epoch ==> 57 / 100 train loss 0.06910130729817826
epoch ==> 58 / 100 train loss 0.07175265268787094
epoch ==> 59 / 100 train loss 0.06715061082302229
epoch ==> 60 / 100 train loss 0.0632058329799253
epoch ==> 61 / 100 train loss 0.06365441146266201
epoch ==> 62 / 100 train loss 0.061902236679325935
epoch ==> 63 / 100 train loss 0.06273865906278724
epoch ==> 64 / 100 train loss 0.058384255384621414
epoch ==> 65 / 100 train loss 0.05656775795733151
epoch ==> 66 / 100 train loss 0.05559660955939604
epoch ==> 67 / 100 train loss 0.05519875900253006
epoch ==> 68 / 100 train loss 0.05136132242320025
epoch ==> 69 / 100 train loss 0.05249214585384597
epoch ==> 70 / 100 train loss 0.050045653246343136
epoch ==> 71 / 100 train loss 0.05093756556996833
epoch ==> 72 / 100 train loss 0.047049138371063316
epoch ==> 73 / 100 train loss 0.047951991345895374
epoch ==> 74 / 100 train loss 0.04640813908823158
epoch ==> 75 / 100 train loss 0.05371057298844275
epoch ==> 76 / 100 train loss 0.048070524697718414
epoch ==> 77 / 100 train loss 0.04567765076037334
epoch ==> 78 / 100 train loss 0.04101008427855761
epoch ==> 79 / 100 train loss 0.043551310836135046
epoch ==> 80 / 100 train loss 0.03860635310411453
epoch ==> 81 / 100 train loss 0.03755538046117062
epoch ==> 82 / 100 train loss 0.03903025962695803
epoch ==> 83 / 100 train loss 0.036364570887678346
epoch ==> 84 / 100 train loss 0.03395244758576155
epoch ==> 85 / 100 train loss 0.04263182788196465
epoch ==> 86 / 100 train loss 0.04067036191649411
epoch ==> 87 / 100 train loss 0.03198591431440866
epoch ==> 88 / 100 train loss 0.03206823918077609
epoch ==> 89 / 100 train loss 0.029815968530981438
epoch ==> 90 / 100 train loss 0.03036130339656349
epoch ==> 91 / 100 train loss 0.03253893805262835
epoch ==> 92 / 100 train loss 0.02942130131566006
epoch ==> 93 / 100 train loss 0.027968573626940666
epoch ==> 94 / 100 train loss 0.027164680599842384
epoch ==> 95 / 100 train loss 0.026450747563301222
epoch ==> 96 / 100 train loss 0.031172410873493747
epoch ==> 97 / 100 train loss 0.02612758415710667
epoch ==> 98 / 100 train loss 0.026641031119810497
epoch ==> 99 / 100 train loss 0.026312213917465313
epoch ==> 100 / 100 train loss 0.022546003086735374

In [34]:
# Evaluate 

model.eval()

total_val = 0
correct_val = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb)
        _, predicted_val = torch.max(outputs, 1)

        correct_val  += (predicted_val == yb).sum().item()
        total_val += yb.size(0) # actual sample in each batch

        accuracy = 100 * correct_val / total_val

print("Total Values :", total_val)
print("Correct Values :", correct_val)
print("Validation Accuracy:", accuracy, "%")

Total Values : 180
Correct Values : 171
Validation Accuracy: 95.0 %